---
#   Copyright 2019 Julien Viard de Galbert
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

- name: Install lxc
  apt:
    pkg: lxc
    state: present
  register: lxc_install_register
  tags: lxc-setup

- name: Get version
  shell: 'lxc-info --version'
  when: lxc_install_register is changed or lxc_current_version is undefined
  register: lxc_version_register
  tags: lxc-setup

- name: Set version fact
  when: lxc_version_register is changed
  set_fact:
    lxc_current_version: '{{ lxc_version_register.stdout }}'
    cacheable: yes
  tags: lxc-setup

- name: Configure lxc-net
  when: lxc_net_enable
  template:
    src: lxc-net.j2
    dest: /etc/default/lxc-net
    owner: root
    group: root
    mode: 0644
  register: etc_default_lxc_net
  tags: lxc-setup

# TODO explicit start or use trigger or only explicit enable and trigger start?
- name: Start lxc-net service
  when: etc_default_lxc_net is changed
  service:
    name: lxc-net
    state: restarted
    enabled: yes
  tags: lxc-setup

- name: Configure lxc default.conf
  template:
    src: default.conf.j2
    dest: /etc/lxc/default.conf
    owner: root
    group: root
    mode: 0644
  tags: lxc-setup

- vars:
    lxc_group_name: "{{ group_names | map('regex_search', '^'+lxc_group_prefix+'.*$') | select | list | join('') }}"
  when: lxc_group_name != ''
  block:
  - name: create containers
    with_items: '{% set lxclist=[] -%} {%- for lxc_host in groups[lxc_group_name] -%} {%- if hostvars[lxc_host].get("physical_host", "") == ansible_host and hostvars[lxc_host]["container_name"] is defined -%} {{ lxclist.append(lxc_host) }} {%- endif -%} {%- endfor%}{{lxclist | list}}'
    loop_control:
      loop_var: lxc_host
    include_tasks: create-container.yml
  tags: lxc-create
